version: 2.1

workflows:
  version: 2

  # The build workflow will build a preview for the site, intended for PRs
  build:
    jobs:
      - build-site:
          filters:
            branches:
              ignore: master

build_jekyll: &build_jekyll
    name: Jekyll Build
    command: |
        echo "Building RSE Blog for Preview"
        cp ~/chenglabwiki.github.io/.circleci/circle_urls.sh ~/chenglabwiki.github.io/circle_urls.sh
        cd ~/chenglabwiki.github.io
        chmod u+x circle_urls.sh
        bash circle_urls.sh              
        bundle exec jekyll build
        
jobs:
  build-site:
    docker:
      - image: circleci/ruby:2.4.1
    working_directory: ~/chenglabwiki.github.io
    environment:
      - JEKYLL_ENV: production
      - NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      - BUNDLE_PATH: ~/chenglabwiki.github.io/vendor/bundle
    steps:
      - checkout
      - restore_cache:
          keys:
          - rubygems-v1
      - run:
          name: Bundle Install
          command: |
              cd ~/chenglabwiki.github.io
              bundle check || bundle install
      - save_cache:
          key: rubygems-v1
          paths:
            - vendor/bundle
      - run: *build_jekyll
      - store_artifacts:
          path: ~/chenglabwiki.github.io/_site
          destination: 
